### ISSUE TITLE
Explain Different Approaches to Asynchronous Calls

### ISSUE THREAD

**Issue by mickeyl** [brightdigit/MistKit#65]
I may be daft, but I can't figure out how this works. I'm using an example derived from your main page:

```
import MistKit
import MistKitNIOHTTP1Token

let container = "…" // a valid container
let token = "" // a valid token

let connection = MKDatabaseConnection(
        container: container,
        apiToken: token,
        environment: .production)

let manager = MKTokenManager(
        storage: MKUserDefaultsStorage(),
        client: MKNIOHTTP1TokenClient(bindTo: .ipAddress(host: "127.0.0.1", port: 7000))
)

let database = MKDatabase(
        connection: connection,
        tokenManager: manager
)


let query = MKAnyQuery(recordType: "LTOBD2CaptureFile", desiredKeys: ["model"])

let request = FetchRecordQueryRequest(
        database: .public,
        query: FetchRecordQuery(query: query)
)

database.perform(request: request) { result in
    do {
        try print(result.get().records.information)

    } catch {
        print("an error occured: \(error)")
        return
    }
}
```

Apart from printing `{"query":{"recordType":"LTOBD2CaptureFile"},"desiredKeys":["model"],"numbersAsStrings":true}`, the code doesn't seem to do anything. Isn't there some kind of mainloop I have to spin for the requests to be performed?

**Comment by leogdion** [comment]
Hey @mickeyl 

You are correct you need to handle the _mainloop_ somehow.
Would it be helpful to add something like this to the documentation?

```swift
database.perform(request: request) { result in
    do {
        try print(result.get().records.information)
    } catch {
        print("an error occured: \(error)")
        return
    }
    CFRunLoopStop(CFRunLoopGetMain())
}
CFRunLoopRun()
```

My worry is that this is specific for a command-line application as opposed to a server-side application. I'd prefer to let the user handle the async call in their own manner (i.e. `EventLoopFuture`, `DispatchSemaphore`, `DispatchGroup`, `RunLoop` etc...). I assume this is command-line application, correct?

Regardless, let me know if this fixes your issue.

**Comment by mickeyl** [comment]
Thanks a lot, adding the runloop made it work for me. I think at least a quick side remark that highlights the necessity for a runloop (which, yes, is a given for server-side apps, but as you guessed I'm working on a command-line tool) would be helpful.

**Comment by leogdion** [comment]
I'm going to reopen the issue so I keep note of needing to amend the documentation. Thanks @mickeyl
